/*CREATE DATABASE Inventory

use Inventory;*/

CREATE TABLE ALMACEN(

ID_ALMACEN INT  IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION NVARCHAR(200)  NOT NULL,
CAPACIDAD INT NOT NULL,
ESTADO BIT DEFAULT (1) NOT NULL,
UBICACION NVARCHAR(200) NOT NULL

);


CREATE TABLE CATEGORIA (

ID_CATEGORIA INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE_CATEGORIA NVARCHAR (50) NOT NULL,
DESCRIPCION NVARCHAR (200) NOT NULL,
ESTADO BIT DEFAULT (1)


);


CREATE TABLE ARTICULO (

ID_ARTICULO INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE_ARTICULO NVARCHAR (50) NOT NULL UNIQUE, 
DESCRIPCION NVARCHAR(200) NOT NULL,
MARCA NVARCHAR (50) NOT NULL, 
PRECIO DECIMAL (11,2) NOT NULL,
ESTADO BIT DEFAULT (1) NOT NULL,
FECHA_ENTRADA DATE NOT NULL,
STOCK INT NOT NULL,
ID_ALMACEN INT FOREIGN KEY REFERENCES ALMACEN(ID_ALMACEN),
ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID_CATEGORIA) 
);


CREATE TABLE PERSONA(
	ID_PERSONA INTEGER IDENTITY(1,1) PRIMARY KEY,
	TIPO_PERSONA NVARCHAR(20) NOT NULL,
	NOMBRE NVARCHAR(150) NOT NULL,
	TIPO_DOCUMENTO NVARCHAR(20) NULL,
	NUM_DOCUMENTO NVARCHAR(20) NULL,
	DIRECCION NVARCHAR(70) NULL,
	TELEFONO NVARCHAR(20) NULL,
	EMAIL NVARCHAR(50) NULL

);

CREATE TABLE ROL(
	ID_ROL INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMBRE NVARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(100) NULL,
	CONDICION BIT DEFAULT(1)
);



CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY ,
	NOMBRE NVARCHAR(100) NOT NULL,
	TIPO_DOCUMENTO NVARCHAR(20) NULL,
	NUM_DOCUMENTO NVARCHAR(20) NULL,
	DIRECCION NVARCHAR(70) NULL,
	TELEFONO NVARCHAR(20) NULL,
	EMAIL NVARCHAR(70) NOT NULL,
	PASSWORD_HASH VARBINARY NOT NULL,
	PASSWORD_SALT VARBINARY NOT NULL,
	CONDICION BIT DEFAULT(1),
	ID_ROL INT FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);


CREATE TABLE ENTRADA(
	ID_ENTRADA INT IDENTITY(1,1) PRIMARY KEY,
	TIPO_COMPROBANTE NVARCHAR(20) NOT NULL,
	SERIE_COMPROBANTE NVARCHAR(7) NULL,
	NUM_COMPROBANTE NVARCHAR (10) NOT NULL,
	FECHA_HORA DATETIME NOT NULL,
	IMPUESTO DECIMAL (4,2) NOT NULL,
	TOTAL DECIMAL (11,2) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	ID_PROVEEDOR INT NOT NULL FOREIGN KEY (ID_PROVEEDOR) REFERENCES PERSONA (ID_PERSONA),
	ID_USUARIO INT NOT NULL FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);


CREATE TABLE DETALLE_ENTRADA(

	ID_DETALLE_ENTRADA INT IDENTITY(1,1) PRIMARY KEY,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(11,2) NOT NULL,
	ID_INGRESO INT  NOT NULL FOREIGN KEY (ID_INGRESO) REFERENCES ENTRADA(ID_ENTRADA) ON DELETE CASCADE,
	ID_ARTICULO INT NOT NULL FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO)
);



CREATE TABLE SALIDA(
	ID_SALIDA INT IDENTITY (1,1) PRIMARY KEY ,
	TIPO_COMPROBANTE NVARCHAR(20) NOT NULL,
	SERIE_COMPROBANTE NVARCHAR(7) NULL,
	NUM_COMPROBANTE VARCHAR (10) NOT NULL,
	FECHA_HORA DATETIME NOT NULL,
	IMPUESTO DECIMAL (4,2) NOT NULL,
	TOTAL DECIMAL (11,2) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	ID_CLIENTE INT NOT NULL FOREIGN KEY (ID_CLIENTE) REFERENCES PERSONA (ID_PERSONA),
	ID_USUARIO INT NOT NULL FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);


CREATE TABLE DETALLE_SALIDA(
	ID_DETALLE_VENTA INT IDENTITY (1,1) PRIMARY KEY ,
	CANTIDAD INT NOT NULL,
	PRECIO DECIMAL(11,2) NOT NULL,
	DESCUENTO DECIMAL(11,2) NOT NULL,
	ID_VENTA INT NOT NULL FOREIGN KEY (ID_VENTA) REFERENCES SALIDA (ID_SALIDA) ON DELETE CASCADE,
	ID_ARTICULO INT NOT NULL FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO)
);


